### ISSUE TITLE
np.sqrt(total_norm.cpu()) raising AttributeError on train.py

### ISSUE THREAD

**Issue by lucas0** [wjko2/Domain-Agnostic-Sentence-Specificity-Prediction#2]
Traceback (most recent call last):
  File "train.py", line 488, in <module>
    train_acc = trainepoch(epoch)
  File "train.py", line 443, in trainepoch
    total_norm = np.sqrt(total_norm.cpu())
AttributeError: 'float' object has no attribute 'cpu'

Is there a particular reason for you to use `.cpu()` here? Seems like it could be removed.

**Comment by wjko2** [comment]
Also looks like a pytorch version issue
